name: Update userscript in release

on:
  release:
    types: [published, edited]

permissions:
  contents: write

jobs:
  upload-userscript:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest script from main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Upload script to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.event.release.tag_name }}" \
            "ITD-Visual-Pack.user.js" \
            --clobber
