name: Update userscript in release

on:
  release:
    types: [published, edited]
  push:
    branches: [main]
    paths: [ITD-Visual-Pack.user.js]

permissions:
  contents: write

jobs:
  upload-userscript:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest script from main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Upload script to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ github.event.release.tag_name || 'ITD-X' }}
        run: |
          gh release upload "$TAG" \
            "ITD-Visual-Pack.user.js" \
            --clobber
