name: Add userscript to release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  upload-userscript:
    runs-on: ubuntu-latest

    steps:
      - name: Get files from main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Upload userscript to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: ITD-Visual-Pack.user.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
